[env:seeed_xiao_esp32s3]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino
monitor_speed = 115200

lib_deps =
    ArduinoJson
    https://github.com/esp32beans/switch_ESP32.git

build_flags =
    -DBOARD_HAS_NATIVE_USB
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DFIRMWARE_VERSION='"1.0.0"'
